### PR TITLE
An attempt to fix https://github.com/lambdacube3d/lambdacube-compiler/issues/11

### PR DESCRIPTION
**Pull request by deepfire**
This seems to work for my test application.

EDIT: there was a controversy, due to launching a different application and thinking that something is broken.

### CODE REVIEW

**Comment by deepfire** [comment]
I have tried an unadulterated version of `lambdacube3d` with a version of `megaparsec` just before the introduction of the RWST instance: https://github.com/mrkkrp/megaparsec/commit/97257f3c7f906ce1d43cbe752704f707e8173830#diff-7762a64005e439e93f28d5c9a983baa9

..yet the application black screen persists.  So, this fix isn't the problem in my particular case..

**Comment by csabahruska** [comment]
What version of megaparsec do you use?

**Comment by deepfire** [comment]
The conflicting instance is introduced in upstream commit https://github.com/mrkkrp/megaparsec/commit/dd2386aafc6b23553dda3ae0bc97cba80cf4124a#diff-7762a64005e439e93f28d5c9a983baa9

**Comment by csabahruska** [comment]
sure but there is a [megaparsec <5.2](https://github.com/lambdacube3d/lambdacube-compiler/blob/master/lambdacube-compiler.cabal#L104) constraint in the cabal file

**Comment by deepfire** [comment]
Sigh, yes, but.. I had to "jailbreak", using Nix terms, because I had to go with the latest `nixpkgs`.. Of course, with the benefit of the hindsight I would have overridden `megaparsec` to an earlier version -- but that wouldn't have been free either, since it would've meant rebuilding things from source..

It's not a simple picture, and I agree, personal inclinations did play a role in this.

But in any case, we now have an option to have compat with the latest megaparsec : -)

**Comment by csabahruska** [comment]
I see. I'm not a nix user. Usually I use `stack` or `cabal new-build` in local sandboxed mode.

**Comment by csabahruska** [comment]
Why did you close the issue? Did you solve it?

**Comment by deepfire** [comment]
The latest `lambdacube-compiler` from builds with MegaParsec 6.3.0, with my PR -- so I've closed that issue.

**Pull request closed without merging**
